# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  lp-is-gamestore

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the project: Gamestore.Serverless
  GamestoreServerlessFunctionsGetAvailableGamesAsyncGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootGet
      SyncedEventProperties:
        RootGet:
          - Path
          - Method
    Properties:
      Runtime: dotnet8
      CodeUri: ./Serverless/src/Gamestore.Serverless/
      MemorySize: 128
      Timeout: 60
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: Gamestore.Serverless::Gamestore.Serverless.Functions_GetAvailableGamesAsync_Generated::GetAvailableGamesAsync
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /get-available-games
            Method: GET
      Architectures:
        - x86_64
      Description: A Lambda function that returns a static string.
 
Outputs:
  ApiURL:
    Description: API endpoint URL for Prod environment
    Value:
      Fn::Sub: https://ad49xs3450.execute-api.us-east-1.amazonaws.com/
